import type { DetailPreset, ReportPreset } from "./types";

export const SUMMARY_PRESETS: ReportPreset[] = [
  {
    id: "military-specialty-distribution",
    title: "Распределение по ВУС",
    description: "Количество кандидатов и курсантов по военно-учетным специальностям.",
    chartType: "bar",
    query: {
      metrics: [{ field: "student_count", aggregation: "count" }],
      dimensions: ["military_specialty"],
      filters: [],
      sort: [{ field: "student_count", direction: "desc" }],
      limit: 100,
    },
  },
  {
    id: "commissariats-by-platoon",
    title: "Военкоматы по взводам",
    description: "Распределение личного состава по военным комиссариатам внутри взводов.",
    chartType: "bar",
    query: {
      metrics: [{ field: "student_count", aggregation: "count" }],
      dimensions: ["platoon", "military_commissariat"],
      filters: [],
      sort: [{ field: "student_count", direction: "desc" }],
      limit: 100,
    },
  },
  {
    id: "selection-statuses",
    title: "Статусы отбора",
    description: "Сколько записей находится в каждом статусе конкурсного отбора.",
    chartType: "pie",
    query: {
      metrics: [{ field: "student_count", aggregation: "count" }],
      dimensions: ["status"],
      filters: [],
      sort: [{ field: "student_count", direction: "desc" }],
      limit: 100,
    },
  },
  {
    id: "avg-final-by-group",
    title: "Средний итоговый балл по группам",
    description: "Сравнение среднего итогового результата между учебными группами.",
    chartType: "bar",
    query: {
      metrics: [{ field: "final_result", aggregation: "avg" }],
      dimensions: ["study_group"],
      filters: [],
      sort: [{ field: "avg_final_result", direction: "desc" }],
      limit: 100,
    },
  },
  {
    id: "avg-grade-by-institute",
    title: "Средний балл по институтам",
    description: "Средняя успеваемость по 100-балльной шкале в разрезе институтов.",
    chartType: "bar",
    query: {
      metrics: [{ field: "grade100", aggregation: "avg" }],
      dimensions: ["institute"],
      filters: [],
      sort: [{ field: "avg_grade100", direction: "desc" }],
      limit: 100,
    },
  },
  {
    id: "physical-by-platoon",
    title: "Физподготовка по взводам",
    description: "Средняя сумма баллов физической подготовки по взводам.",
    chartType: "line",
    query: {
      metrics: [{ field: "total_points", aggregation: "avg" }],
      dimensions: ["platoon"],
      filters: [],
      sort: [{ field: "platoon", direction: "asc" }],
      limit: 100,
    },
  },
  {
    id: "fitness-categories",
    title: "Категории годности",
    description: "Распределение по категориям годности к военной службе.",
    chartType: "pie",
    query: {
      metrics: [{ field: "student_count", aggregation: "count" }],
      dimensions: ["fitness_category"],
      filters: [],
      sort: [{ field: "student_count", direction: "desc" }],
      limit: 100,
    },
  },
];

export const DETAIL_PRESETS: DetailPreset[] = [
  {
    id: "people-by-platoon",
    title: "Список людей по взводу",
    description: "ФИО, взвод, военкомат, ВУС и итоговый балл для выбранного взвода.",
    columns: [
      "full_name",
      "platoon",
      "military_commissariat",
      "military_specialty",
      "final_result",
    ],
    query: {
      columns: [
        "full_name",
        "platoon",
        "military_commissariat",
        "military_specialty",
        "final_result",
      ],
      filters: [],
      sort: [{ field: "final_result", direction: "desc" }],
      limit: 100,
    },
  },
  {
    id: "people-by-commissariat",
    title: "Список людей по военкомату",
    description: "Детальная выгрузка людей с учебной группой, взводом и ВУС.",
    columns: [
      "full_name",
      "study_group",
      "platoon",
      "military_commissariat",
      "military_specialty",
      "status",
    ],
    query: {
      columns: [
        "full_name",
        "study_group",
        "platoon",
        "military_commissariat",
        "military_specialty",
        "status",
      ],
      filters: [],
      sort: [{ field: "full_name", direction: "asc" }],
      limit: 100,
    },
  },
  {
    id: "enrolled-by-specialty",
    title: "Зачисленные по ВУС",
    description: "Список зачисленных с ВУС, группой и итоговыми показателями.",
    columns: [
      "full_name",
      "study_group",
      "military_specialty",
      "status",
      "grade100",
      "total_points",
      "final_result",
    ],
    query: {
      columns: [
        "full_name",
        "study_group",
        "military_specialty",
        "status",
        "grade100",
        "total_points",
        "final_result",
      ],
      filters: [{ field: "status", operator: "eq", value: "ENROLLED" }],
      sort: [{ field: "final_result", direction: "desc" }],
      limit: 100,
    },
  },
];
